Update jenkinsfile-2

diff --git a/jenkinsfile-2 b/jenkinsfile-2
--- a/jenkinsfile-2
+++ b/jenkinsfile-2
@@ -6,20 +6,28 @@ pipeline {
         REGISTRY = "docker.io"
         DOCKER_CREDENTIALS_ID = "Docker"
         GITHUB_CREDENTIALS_ID = "Git"
-        APP_DIR = ${WORKSPACE}
     }
 
     stages {
+        stage('Set Environment Variables') {
+            steps {
+                script {
+                    env.APP_DIR = env.WORKSPACE  // Correct way to set APP_DIR
+                    echo "APP_DIR is set to: ${env.APP_DIR}"
+                }
+            }
+        }
+
         stage('Checkout Code') {
             steps {
-                git credentialsId: GITHUB_CREDENTIALS_ID, url: 'https://github.com/Kathir37/jenkins.git', branch: 'main'
+                git credentialsId: env.GITHUB_CREDENTIALS_ID, url: 'https://github.com/Kathir37/jenkins.git', branch: 'main'
             }
         }
 
         stage('Build Docker Image') {
             steps {
                 script {
-                    sh "cd $APP_DIR && docker build -t $IMAGE_NAME:latest ."
+                    sh "cd ${env.APP_DIR} && docker build -t ${env.IMAGE_NAME}:latest ."
                 }
             }
         }
@@ -27,8 +35,8 @@ pipeline {
         stage('Login to Docker Registry') {
             steps {
                 script {
-                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
-                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
+                    withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
+                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin ${env.REGISTRY}'
                     }
                 }
             }
@@ -37,7 +45,7 @@ pipeline {
         stage('Push Image to Docker Registry') {
             steps {
                 script {
-                    sh "docker push $IMAGE_NAME:latest"
+                    sh "docker push ${env.IMAGE_NAME}:latest"
                 }
             }
         }
@@ -45,7 +53,12 @@ pipeline {
         stage('Deploy using Docker Compose') {
             steps {
                 script {
-                    sh "cd $APP_DIR && docker-compose down && docker-compose up -d"
+                    sh '''
+                        set -e  # Stop execution if any command fails
+                        cd ${APP_DIR}
+                        docker-compose down
+                        docker-compose up -d
+                    '''
                 }
             }
         }
@@ -53,7 +66,7 @@ pipeline {
 
     post {
         success {
-            echo 'Pipeline executed successfully! '
+            echo 'Pipeline executed successfully!'
         }
         failure {
             echo 'Pipeline failed! Check the logs for errors.'
